[package]
name = "khaki"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "core/main.rs"
name = "khaki"

[workspace]
members = [
  "ir",
  "parser",
  "flatten",
  "codegen"
]

[dependencies]
ir = { path = "ir" }
parser = { path = "parser" }
flatten = { path = "flatten" }
codegen = { path = "codegen" }
